### Create User
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "invincible",
  "email": "guest@gmail.com",
  "password": "guest_password",
  "firstName": "Mark",
  "lastName": "Grayson"
}

### Create Another User
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "bruce",
  "email": "banner@gmail.com",
  "password": "test_password",
  "firstName": "Bruce",
  "lastName": "Banner"
}

### Get Current User
GET http://localhost:3000/api/users/me
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

### Get User (Invalid)
GET http://localhost:3000/api/users/bruce2
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

?? status == 404
?? body error includes not found

### Get User (Valid) - should contain profile data & posts
GET http://localhost:3000/api/users/bruce
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

?? status == 200
?? body firstName includes John

### Update User Data
POST http://localhost:3000/api/users/update
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

{
  "firstName": "Changed Mark"
}

?? status == 200

### Update Password (missing data failure)
POST http://localhost:3000/api/users/update
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

{
  "currentPassword": "guest_password"
}

?? status == 400

### Update Password (same password failure)
POST http://localhost:3000/api/users/update
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

{
  "currentPassword": "guest_password",
  "newPassword": "guest_password"
}

?? status == 400
?? body error includes same password

### Update Password (wrong password failure)
POST http://localhost:3000/api/users/update
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

{
  "currentPassword": "wrong_password",
  "newPassword": "new_password"
}

?? status == 400
?? body error includes wrong password

### Update Password (success)
POST http://localhost:3000/api/users/update
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

{
  "currentPassword": "guest_password",
  "newPassword": "new_password"
}

?? status == 200

### Upload Image (success)
POST http://localhost:3000/api/users/update
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

--WebKitFormBoundary
Content-Disposition: form-data; name="firstName"

Mark
--WebKitFormBoundary
Content-Disposition: form-data; name="profileImage"; filename="favicon-32x32.png"
Content-Type: image/png

< ../frontend/public/favicon-32x32.png
--WebKitFormBoundary--

?? status == 200

### Follow / Unfollow User
POST http://localhost:3000/api/users/follow/bruce
Content-Type: application/json
Cookie: {{$global.accessToken}}
Cookie: {{$global.refreshToken}}

?? status == 200
